// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyIqGBWRTXkzesoTWJ8fSMWVX-3sEshng',
    appId: '1:773351997814:web:61452a7e4b41d8db047a57',
    messagingSenderId: '773351997814',
    projectId: 'crud-flutterbah',
    authDomain: 'crud-flutterbah.firebaseapp.com',
    storageBucket: 'crud-flutterbah.firebasestorage.app',
    measurementId: 'G-PBZE4Q1LNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJMgNuhlxci0WnZI2gNCo-xZ0EXcZgqU8',
    appId: '1:773351997814:android:4e5b91153d797b97047a57',
    messagingSenderId: '773351997814',
    projectId: 'crud-flutterbah',
    storageBucket: 'crud-flutterbah.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyIqGBWRTXkzesoTWJ8fSMWVX-3sEshng',
    appId: '1:773351997814:web:da5899669214e1f9047a57',
    messagingSenderId: '773351997814',
    projectId: 'crud-flutterbah',
    authDomain: 'crud-flutterbah.firebaseapp.com',
    storageBucket: 'crud-flutterbah.firebasestorage.app',
    measurementId: 'G-LWN16Z6GSM',
  );
}
